const S={start:document.getElementById('start'),question:document.getElementById('question'),result:document.getElementById('result')},st={i:0,a:{},r:null};
function show(n){Object.values(S).forEach(x=>x.classList.remove('active'));S[n].classList.add('active');window.scrollTo(0,0)}
function begin(){st.i=0;st.a={};render();show('question')}
function render(){const q=QUESTIONS[st.i];count.textContent=`${st.i+1} / ${QUESTIONS.length}`;bar.style.width=`${((st.i+1)/QUESTIONS.length)*100}%`;section.textContent=q.section;title.textContent=q.title;help.textContent=q.help||'';body.innerHTML='';if(q.type==='choice'){const d=document.createElement('div');d.className='answers';q.choices.forEach(c=>{const b=document.createElement('button');b.className='answer';b.textContent=c;b.onclick=()=>save(q,c);d.appendChild(b)});body.appendChild(d)}else{const f=document.createElement(q.type==='textarea'?'textarea':'input');f.className='field '+(q.type==='textarea'?'textarea':'');f.maxLength=q.max||99;const c=document.createElement('div');c.className='counter';c.textContent=`0 / ${f.maxLength}`;f.oninput=()=>c.textContent=`${f.value.length} / ${f.maxLength}`;const b=document.createElement('button');b.className='primary';b.textContent='次へ';b.onclick=()=>{if(q.required&&!f.value.trim())return;save(q,f.value.trim())};body.append(f,c,b)}back.style.visibility=st.i===0?'hidden':'visible';skip.style.visibility=q.required?'hidden':'visible'}
function save(q,v){st.a[q.id]=v;if(st.i<QUESTIONS.length-1){st.i++;render()}else build()}
function autoCard(){const a=st.a;if(a.no_limits==='世界を旅する'||a.emotion==='自由')return'旅人';if(['家族','仲間'].includes(a.priority))return'橋';if(['文章・小説','音楽','絵・写真'].includes(a.learning))return'星';if(['自信のなさ','年齢への思い込み'].includes(a.blocker))return'夜明け';if(a.priority==='安心'||a.emotion==='安心')return'羅針盤';return'灯火'}
function unit(current,goal,project,actions){return{current,goal,main_project:project,small_actions:actions}}
function build(){const a=st.a,phase={'20代以下':'基盤形成期','30代':'拡張期','40代':'転換期','50代':'再設計期','60代':'再点火期','70代以上':'充実・継承期'}[a.age],card=a.card==='自動で選ぶ'?autoCard():a.card,cd=CARD_DATA[card];const hAct={'かなり元気':['週1回、新しい運動を試す','睡眠時間を記録する'],'おおむね元気':['週2回30分歩く','疲労を翌日に残さない'],'少し気になる':['食事を一つだけ見直す','週2回軽く歩く'],'体力が落ちた':['毎日10分歩く','脚と腰を軽く伸ばす'],'生活改善が必要':['通院・検査予定を確認','夜の習慣を一つ変える'],'治療や通院を優先している':['医療方針を最優先','無理のない楽しみを確保']}[a.health];const units={health:unit(a.health,a.health_goal,`${a.health_goal}ための基礎体力設計`,hAct),learning:unit(a.learning,a.future,`${a.learning}を生活に定着させる`,['週1回30分だけ取り組む','小さな成果を一つ残す']),play:unit(a.hobby,a.no_limits,`${a.hobby}から人生の充電を増やす`,['今月一度予定に入れる','体験を写真か短文で残す']),money:unit(a.money,a.money_goal,`${a.money_goal}ための資源設計`,['専用積立を始める','固定費を一つ確認する']),time:unit(a.time,a.future,`${a.time}を先に確保する`,['週予定へ先に書く','減らす用事を一つ決める'])};st.r={version:'1.1',profile:{nickname:a.nickname,age:a.age,life_phase:phase,gender:a.gender,occupation:a.occupation,family:a.family},design_theme:`${a.priority}を土台に、${a.emotion}を取り戻す設計`,bottleneck:a.blocker,success_condition:a.future,compass:{card,keywords:cd.keywords,message:cd.message},units,drawing_option:a.drawing||'',answers:a};renderResult();show('result')}
function renderResult(){const r=st.r;resultTitle.textContent=`${r.profile.nickname}さんの人生再点火設計書`;summary.textContent=`${r.profile.life_phase}にある現在地から、${r.success_condition}へ向かうための基本設計です。`;cardTitle.textContent=r.compass.card;cardMessage.textContent=r.compass.message;theme.textContent=r.design_theme;bottleneck.textContent=r.bottleneck;success.textContent=r.success_condition;const labels={health:'健康ユニット',learning:'創造・学習ユニット',play:'遊び・体験ユニット',money:'資産設計ユニット',time:'時間設計ユニット'};units.innerHTML='';Object.entries(r.units).forEach(([k,u])=>{const e=document.createElement('article');e.className='unit';e.innerHTML=`<h4>${labels[k]}</h4><p><strong>現在地：</strong>${u.current}</p><p><strong>目標：</strong>${u.goal}</p><p><strong>メインプロジェクト：</strong>${u.main_project}</p><p><strong>スモールアクション：</strong><br>・${u.small_actions[0]}<br>・${u.small_actions[1]}</p>`;units.appendChild(e)});json.textContent=JSON.stringify(r,null,2)}
function promptText(){return`以下の人生設計書をもとに、A4横の「人生再点火設計図」を画像として作成してください。AIは内容を再設計せず、この設計書に従って製図してください。\n\n${JSON.stringify(st.r,null,2)}`}
async function cp(t,m){try{await navigator.clipboard.writeText(t);msg.textContent=m}catch{msg.textContent='コピーできませんでした'}}
startBtn.onclick=begin;back.onclick=()=>{if(st.i>0){st.i--;render()}};skip.onclick=()=>save(QUESTIONS[st.i],'');restart.onclick=begin;copyJson.onclick=()=>cp(JSON.stringify(st.r,null,2),'JSONをコピーしました');copyPrompt.onclick=()=>cp(promptText(),'設計図用文章をコピーしました');download.onclick=()=>{const b=new Blob([JSON.stringify(st.r,null,2)],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='life-restart-blueprint.json';a.click();URL.revokeObjectURL(u)};
