const screens={start:document.getElementById("start-screen"),question:document.getElementById("question-screen"),result:document.getElementById("result-screen"),report:document.getElementById("report-screen")};
const state={index:0,answers:{},result:null};
function showScreen(name){Object.values(screens).forEach(s=>s.classList.remove("active"));screens[name].classList.add("active");window.scrollTo(0,0)}
function startDiagnosis(){state.index=0;state.answers={};renderQuestion();showScreen("question")}
function renderQuestion(){const q=QUESTIONS[state.index];document.getElementById("question-count").textContent=`${state.index+1} / ${QUESTIONS.length}`;document.getElementById("progress-bar").style.width=`${((state.index+1)/QUESTIONS.length)*100}%`;document.getElementById("question-section").textContent=q.section;document.getElementById("question-title").textContent=q.title;document.getElementById("question-help").textContent=q.help||"";const body=document.getElementById("question-body");body.innerHTML="";
if(q.type==="choice"){const list=document.createElement("div");list.className="answer-list";q.choices.forEach(c=>{const b=document.createElement("button");b.className="answer-button";b.textContent=c;b.onclick=()=>saveAnswer(q,c);list.appendChild(b)});body.appendChild(list)}else{const f=document.createElement(q.type==="textarea"?"textarea":"input");f.className=q.type==="textarea"?"textarea-field":"input-field";f.maxLength=q.maxLength||99;const counter=document.createElement("div");counter.className="counter";counter.textContent=`0 / ${f.maxLength}`;f.oninput=()=>counter.textContent=`${f.value.length} / ${f.maxLength}`;const b=document.createElement("button");b.className="primary-button input-submit";b.textContent="次へ";b.onclick=()=>{if(q.required&&!f.value.trim())return;saveAnswer(q,f.value.trim())};body.append(f,counter,b)}
document.getElementById("back-button").style.visibility=state.index===0?"hidden":"visible";document.getElementById("skip-button").style.visibility=q.required?"hidden":"visible"}
function saveAnswer(q,v){state.answers[q.id]=v;if(state.index<QUESTIONS.length-1){state.index++;renderQuestion()}else calculateResult()}
function calcDimensions(){const a=state.answers;const healthMap={"かなり元気":92,"おおむね元気":78,"少し気になる":62,"体力が落ちた":46,"生活改善が必要":35,"治療や通院を優先している":30};const financeMap={"余裕がある":92,"普通に生活できる":75,"少し節約が必要":60,"貯金を増やしたい":50,"収入源を増やしたい":42,"かなり不安がある":28};let d={health:healthMap[a.health]||55,finance:financeMap[a.money]||55,creativity:45,adventure:45,connection:45,balance:50};if(["文章・小説","音楽","絵・写真","AI・デジタル"].includes(a.learning))d.creativity+=35;if(["旅行・散歩","釣り・アウトドア"].includes(a.hobby))d.adventure+=35;if(["家族","仲間"].includes(a.priority))d.connection+=35;if(["安心","健康"].includes(a.priority))d.balance+=25;Object.keys(d).forEach(k=>d[k]=Math.max(20,Math.min(96,d[k])));return d}
function calculateResult(){const d=calcDimensions();const scores={seeker:d.creativity*.3+d.balance*.2,creator:d.creativity*.7,adventurer:d.adventure*.7,connector:d.connection*.7,balancer:d.balance*.4+d.health*.2+d.finance*.2};if(["読書","資格・勉強"].includes(state.answers.learning))scores.seeker+=25;const typeKey=Object.entries(scores).sort((a,b)=>b[1]-a[1])[0][0];const type=TYPES[typeKey];const weak=Object.entries(d).sort((a,b)=>a[1]-b[1])[0];let card;if((state.answers.destiny_card||"").trim())card={title:"あなた自身が選んだカード",message:state.answers.destiny_card.trim()};else card=CARDS[Math.floor(Math.random()*CARDS.length)];state.result={version:"1.0",profile:{nickname:state.answers.nickname,age:state.answers.age,gender:state.answers.gender,appearance:state.answers.appearance,catchcopy:state.answers.catchcopy},type:type.name,type_key:typeKey,world:state.answers.world,dimensions:d,weakest_dimension:{key:weak[0],label:DIMENSION_LABELS[weak[0]],score:weak[1]},first_action:type.action,compass_card:card,answers:state.answers};renderResult(type,d,weak,card);showScreen("result")}
function bars(id,d){const c=document.getElementById(id);c.innerHTML="";Object.entries(d).forEach(([k,v])=>{c.innerHTML+=`<div class="score-row"><div class="score-head"><span>${DIMENSION_LABELS[k]}</span><strong>${v}</strong></div><div class="score-track"><div class="score-fill" style="width:${v}%"></div></div></div>`})}
function renderResult(type,d,weak,card){document.getElementById("result-icon").textContent=type.icon;document.getElementById("result-type").textContent=type.name;document.getElementById("result-catch").textContent=type.catch;document.getElementById("result-description").textContent=type.description;document.getElementById("result-strength").textContent=type.strength;document.getElementById("result-adjustment").textContent=`${DIMENSION_LABELS[weak[0]]}を少し整えると、全体が動きやすくなります。`;document.getElementById("result-action").textContent=type.action;document.getElementById("card-title").textContent=card.title;document.getElementById("card-message").textContent=card.message;document.getElementById("result-json").textContent=JSON.stringify(state.result,null,2);bars("score-bars",d)}
function renderReport(){const r=state.result,t=TYPES[r.type_key];document.getElementById("report-type").textContent=r.type;document.getElementById("report-catch").textContent=t.catch;document.getElementById("report-description").textContent=t.description;document.getElementById("report-card-title").textContent=r.compass_card.title;document.getElementById("report-card-message").textContent=r.compass_card.message;document.getElementById("report-health").textContent="動き続けるための土台として、睡眠・軽い運動・休養のどれか一つを整えます。";document.getElementById("report-creativity").textContent="体験や学びを、短い記録や小さな作品として残します。";document.getElementById("report-adventure").textContent="大きな旅を待たず、近場の未知を一つ増やします。";document.getElementById("report-warning-title").textContent=`要調整ポイント：${r.weakest_dimension.label}`;document.getElementById("report-warning").textContent="最も低い項目を一度に変えず、小さな改善を一つだけ選びます。";document.getElementById("report-first-action").textContent=r.first_action;document.getElementById("report-future").textContent=state.answers.future;document.getElementById("report-quote").textContent=state.answers.quote||"人生は、いつでも再設計できる。";bars("report-score-bars",r.dimensions);const p=document.getElementById("report-policy");p.innerHTML="<div>知る</div><span>→</span><div>整える</div><span>→</span><div>試す</div><span>→</span><div>続ける</div>";showScreen("report")}
async function copyText(t,m){await navigator.clipboard.writeText(t);document.getElementById("copy-message").textContent=m}
function promptText(){return `以下の診断結果をもとに、人生再点火設計図を作成してください。\n\n${JSON.stringify(state.result,null,2)}`}
document.getElementById("start-button").onclick=startDiagnosis;document.getElementById("back-button").onclick=()=>{if(state.index>0){state.index--;renderQuestion()}};document.getElementById("skip-button").onclick=()=>saveAnswer(QUESTIONS[state.index],"");document.getElementById("restart-button").onclick=startDiagnosis;document.getElementById("show-report-button").onclick=renderReport;document.getElementById("back-result-button").onclick=()=>showScreen("result");document.getElementById("print-button").onclick=()=>window.print();document.getElementById("copy-json-button").onclick=()=>copyText(JSON.stringify(state.result,null,2),"JSONをコピーしました");document.getElementById("copy-prompt-button").onclick=()=>copyText(promptText(),"GPT用文章をコピーしました");document.getElementById("download-json-button").onclick=()=>{const b=new Blob([JSON.stringify(state.result,null,2)],{type:"application/json"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download="life-restart-result.json";a.click();URL.revokeObjectURL(u)};
