const QUESTIONS=[
{id:'nickname',section:'設計条件',title:'① 愛称を教えてください',type:'text',max:20,required:true},
{id:'age',section:'設計条件',title:'② 年齢を選んでください',type:'choice',choices:['20代以下','30代','40代','50代','60代','70代以上'],required:true},
{id:'gender',section:'設計条件',title:'③ 性別を選んでください',type:'choice',choices:['男性','女性','その他','回答しない'],required:true},
{id:'occupation',section:'設計条件',title:'④ 現在の立場・職業に近いものは？',type:'choice',choices:['会社員','自営業・フリーランス','パート・アルバイト','家事・育児中心','退職後','学生','その他'],required:true},
{id:'family',section:'設計条件',title:'⑤ 家族構成に近いものは？',type:'choice',choices:['一人暮らし','夫婦・パートナーと二人','子どもと同居','親と同居','三世代以上','回答しない']},
{id:'fun',section:'現在地',title:'⑥ 今、一番楽しいことは？',type:'choice',choices:['家族との時間','外食・お酒','旅行・散歩','スポーツ','映画・ドラマ','読書・学び','創作・発信','特にない'],required:true},
{id:'problem',section:'現在地',title:'⑦ 今、一番困っていることは？',type:'choice',choices:['健康','お金','時間不足','仕事','家族・人間関係','将来への不安','退屈・生きがい不足','特にない'],required:true},
{id:'health',section:'現在地',title:'⑧ 健康の現在地は？',type:'choice',choices:['かなり元気','おおむね元気','少し気になる','体力が落ちた','生活改善が必要','治療や通院を優先している'],required:true},
{id:'health_goal',section:'現在地',title:'⑨ 健康面で、できるようになりたいことは？',type:'choice',choices:['疲れにくくなりたい','もっと歩きたい','好きな運動を続けたい','食事を楽しみたい','よく眠りたい','今の状態を維持したい'],required:true},
{id:'money',section:'現在地',title:'⑩ お金の現在地は？',type:'choice',choices:['余裕がある','普通に生活できる','少し節約が必要','貯金を増やしたい','収入源を増やしたい','かなり不安がある'],required:true},
{id:'money_goal',section:'現在地',title:'⑪ お金で実現したいことは？',type:'choice',choices:['安心できる貯金','年に一度以上の旅行','趣味へ使える余裕','家族を支える','副収入を作る','今の生活を維持する'],required:true},
{id:'time',section:'現在地',title:'⑫ 今、一番増やしたい時間は？',type:'choice',choices:['自分だけの時間','家族との時間','学ぶ時間','趣味の時間','休む時間','人と会う時間'],required:true},
{id:'hobby',section:'人生のエネルギー',title:'⑬ 一番好きな趣味・遊びは？',type:'choice',choices:['旅行・散歩','スポーツ','釣り・アウトドア','映画・ドラマ','食・お酒','ゲーム','音楽','まだ見つかっていない'],required:true},
{id:'absorption',section:'人生のエネルギー',title:'⑭ 最近、時間を忘れたことは？',type:'choice',choices:['仕事や作業','スポーツ','読書・学び','創作','映画・ドラマ','人との会話','旅行・外出','最近はない'],required:true},
{id:'learning',section:'人生のエネルギー',title:'⑮ これから学びたい・挑戦したいことは？',type:'choice',choices:['資格・仕事の技能','文章・小説','音楽','絵・写真','AI・デジタル','運動・健康','語学・旅行','まだ分からない'],required:true},
{id:'future',section:'未来設計',title:'⑯ 3年後、最も近づきたい暮らしは？',type:'choice',choices:['健康で活動的','家族と安定した生活','好きなことを続けている','収入や貯金が増えている','新しい仕事や役割がある','旅や体験が増えている','作品や成果を残している'],required:true},
{id:'priority',section:'未来設計',title:'⑰ 一番大切にしたいものは？',type:'choice',choices:['健康','家族','仲間','自由','挑戦','安心','創作','お金'],required:true},
{id:'no_limits',section:'未来設計',title:'⑱ 制約がなければ、本当は何をしたい？',type:'choice',choices:['世界を旅する','好きな仕事だけする','作品を発表する','学び直す','家族とゆっくり暮らす','新しい仲間を作る','何もしないで休む','まだ分からない'],required:true},
{id:'emotion',section:'深層インタビュー',title:'⑲ もう一度、強く味わいたい感情は？',type:'choice',choices:['ワクワク','達成感','安心','恋愛','自由','没頭','誇らしさ','挑戦する高揚感'],required:true},
{id:'envy_reason',section:'深層インタビュー',title:'⑳ 最近、誰かを羨ましいと思った理由は？',type:'choice',choices:['自由に生きている','好きなことで成功している','若々しく健康','家族に恵まれている','経済的に余裕がある','専門性や才能がある','仲間が多い','特に羨ましくない'],required:true},
{id:'blocker',section:'深層インタビュー',title:'㉑ 今の自分を止めているものは？',type:'choice',choices:['健康','お金','時間','家族への責任','仕事','自信のなさ','年齢への思い込み','何が止めているか分からない'],required:true},
{id:'card',section:'暗示のカード',title:'㉒ 今、なぜか気になるカードを一枚選んでください',help:'未来を決める占いではありません。今回の設計思想を象徴する暗示として使います。',type:'choice',choices:['灯火','羅針盤','橋','種','夜明け','星','旅人','白紙','自動で選ぶ'],required:true},
{id:'drawing',section:'製図オプション（任意）',title:'図に入れたい要素があれば入力してください',help:'99文字以内。好きな色、服装、猫、海、神社、ピアノなど。',type:'textarea',max:99}
];
